language: python
install: true
python:
  - "2.7"
before_install:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
install:
  - pip install -r requirements.txt
script:
  - python src/lists/test/testNodeChain.py
