language: python
install: true
python:
  - "2.7"
notifications:
  email: false
before_install:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
install:
  - pip install -r requirements.txt
script:
  - python src/lists/test/testNodeChain.py
  - python src/lists/test/testLinkedList.py
  - python src/stack/test/testStackList.py
  - python src/stack/test/testPostfixCalculator.py
  - python src/queue/test/testQueueList.py
  - python src/hash/test/testHashTableArrayNode.py
